### ISSUE TITLE
Pintar un marcador personalizado en un mapa a partir de una Direccion , no tengo las coordenadas

### ISSUE THREAD

**Issue by iabaaba** [esri-es/arcgis-devlabs#22]
Hola,
Deseo pintar un marcador personalizado en un mapa a partir de una Direccion , no tengo las coordenadas.
Gracias, 
PS: Por favor enviar ejemplos to iabaaba@gmail.com

**Comment by hhkaos** [comment]
Perdona que no vi el mensaje (malas fechas).

Aquí tienes la [documentación de la API REST de geocodificación](https://developers.arcgis.com/rest/geocode/api-reference/overview-world-geocoding-service.htm) la que te permite geocodifcar una dirección a coordenadas.

Aunque no se si lo que quieres es un widget para la API de JavaScript: 

* [Search Widget](https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=widgets-search-3d) (API 4.x) 
* O [el de la API 3.x](https://developers.arcgis.com/javascript/3/jssamples/search_basic.html) que además tiene [este tutorial](https://developers.arcgis.com/javascript/3/jshelp/tutorial_search.html).

Luego tenemos una [charla sobre geocodificadores en la comunidad de GeoDevelopers](http://geodevelopers.org/academy/ADJ1jmYjPWA/view).

Espero que con esto sea suficiente.

Un abrazo
