### ISSUE TITLE
seleccionar un polígono

### ISSUE THREAD

**Issue by jordeath** [esri-es/arcgis-devlabs#23]
Hola buenas tardes
Llevo mucho tiempo usando la API de arcgis 3.4 y ahora quiero cambiar a la versión 4.7 pero no logro poder seleccionar un polígono con el mouse con esta versión.
En la versión 3.4 creaba un esri.tasks.QueryTask() en donde especificaba el layer en particular con el cual quería trabajar ejemplo:

```js
queryTask = new esri.tasks.QueryTask("http://miservidor.com:6080/arcgis/rest/services/mapa_uno/MapServer/12")
```

de esta forma con un esri.tasks.Query() podía especificar qué dato obtener de dicha capa

```js
query = new esri.tasks.Query();
query.returnGeometry = true;
query.outFields = ["IDE"];
```

despues con esta funciona en el evento onclick obtenía el dato y dibujaba el poligono

```js
function executeQueryTask(evt) {
  
  query.geometry = evt.mapPoint;
  
  queryTask.execute(query, function(fset) {
    if (fset.features.length === 1) {
      showFeature(fset.features[0],evt);
    } else if (fset.features.length !== 0) {
      showFeatureSet(fset,evt);
    }
  });
}
function showFeature(feature,evt) {
  map.graphics.clear();
  feature.setSymbol(symbol);
  var var_IDE = feature.attributes["IDE"];
  
  map.graphics.add(feature);
  alert(var_identif);
  return false;
}

```

esto es posible hacerlo en la versión 4.7? hasta ahora no logro conseguirlo

desde ya doy las gracias por cualquier ayuda
saludos!

**Comment by hhkaos** [comment]
@jordeath ahora puedes hacer algo parecido, aunque puede lanzar la query contra el servidor o hacer la query contra los datos en el cliente (LayerView).

> **Nota importante**: la sintaxis esri.paquete.modulo ya no funciona con 4.7

Para lanzar la query contra el servidor ahora en lugar de crear un QueryTask de ese modo puedes hacerlo a partir del mismo objeto donde cargaste la capa usando el método [createQuery](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#createQuery) de la capa:

```js
// Get a query object for the layer's current configuration
const queryParams = layer.createQuery();
// set a geometry for filtering features by a region of interest
queryParams.geometry = extentForRegionOfInterest;
// Add to the layer's current definitionExpression
queryParams.where = queryParams.where + " AND TYPE = 'Extreme'";

// query the layer with the modified params object
layer.queryFeatures(queryParams).then(function(results){
  // prints the array of result graphics to the console
  console.log(results.features);
});
```

Aquí tienes un [ejemplo más complejo](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#createQuery)

Y para capturar el evento `click` usar el [método on](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#on) sobre la vista:

```js
view.on("click", function(event){
  // event is the event handle returned after the event fires.
  console.log(event.mapPoint);
});
```

Espero que te sea útil.

Un abrazo

**Comment by jordeath** [comment]
Muchas gracias por tu respuesta!

saludos!

**Comment by hhkaos** [comment]
Cierro el issue, si tienes alguna duda más con la API te recomiendo que uses el grupo de GeoNet ([en español](https://community.esri.com/groups/geodev-spain) o [en inglés](https://community.esri.com/community/developers/web-developers/arcgis-api-for-javascript)) :smile: 

abrazo!
