### ISSUE TITLE
Imprimir un mapa

### ISSUE THREAD

**Issue by jordeath** [esri-es/arcgis-devlabs#24]
En la API 4.8 nos permite activar un widget para imprimir nuestro mapa, en el podemos elegir el formato, dimensiones etc lo cual es bastante bueno, pero mi  problema es que necesito generar un JPG de forma automática, que al apretar un botón lo genere sin la necesidad de ingresar parámetros a un formulario y me devuelva la ruta de la imagen generada. ¿Es posible?
Estoy investigando PrintTask para ver si logro configurar las dimensiones, formato, etc pero no me resulta.

Estoy viendo la doc en esta URL
https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-PrintTask.html#execute

desde ya agradezco a un alma caritativa que me pueda ayudar
saludos!

**Comment by hhkaos** [comment]
Buenas @jordeath , échale un vistazo a [estos dos proyectos](https://github.com/esri-es?utf8=%E2%9C%93&q=static&type=&language=). 

Un abrazo!
